### ISSUE TITLE
Error message for User minlength doesn't correlate with the actual minlength

### ISSUE THREAD

**Issue by chris9740** [supertiger1234/Nertivia-Server#5]
File: https://github.com/supertiger1234/Nertivia-Server/blob/master/src/models/users.js
Line: 51 (Specifically, `minlength: [3, "Username must be more than 5 characters long."],`)

Issue: The actual minimum length for a username is 3 characters, but the error message says it's supposed to be > 5

**Comment by supertiger1234** [comment]
thanks! fixed https://github.com/supertiger1234/Nertivia-Server/commit/a642ec445c4ecdb90f3344cddf37262067fa77e1
